#!/usr/bin/env sh

# reload scripting addition on Dock restart
yabai -m signal --add event=dock_did_restart action="yabai --load-sa"
yabai --load-sa

# enable tiling
yabai -m config layout bsp
yabai -m config auto_balance on
yabai -m config window_gap 10
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10

# manage all normal windows
yabai -m rule --add app="^System Preferences$" manage=off

# applications with custom rules
applications="(Calendar|Mail|Reminders|Notes|Samsung Magician|Discord|Messages|Slack|Firefox|Chrome|Code|Microsoft Word|Preview|Terminal|iTerm2|QuickTime|Player|Spotify|Music|Brave Browser|Kitty|Alacritty|Trello)"

# NOTE: you need to set the settings for the applications in the 
#       list first, or else they don't apply properly and you can end up with
#       some weird border/float/window behaviours

# everything listed gets sent to below layer to prevent 
# them from covering floating applications/popup windows
yabai -m rule --add app="^${applications}$"    manage=on layer=below
